# Generated by Django 3.1.4 on 2021-01-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='item-images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
